server:
  #设置服务器运行时，占用的端口号
  port: 8003

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      #上传的单个文件大小，最大不能超过1024MB
      max-file-size: 1024MB
      #一次请求过程中上传的所有文件总的大小，最大不能超过10240MB
      max-request-size: 10240MB
  #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#配置阿里云VoD（视频点播服务）
aliyun:
  vod:
    file:
      keyid: xxx
      keysecret: xxx


